name: Deploy to Cloud Run (staging)

on:
  push:
    branches: [ "staging" ]

env:
  PROJECT_ID: prodify-474400
  REGION: us-central1
  SERVICE: hello-prodify-staging
  FIRESTORE_DB: prodifydb
  ENV: staging
  BUILD_SA_EMAIL: github-deployer@prodify-474400.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Deploy to Cloud Run (staging)
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region:  ${{ env.REGION }}
          source:  ./hello-prodify
          env_vars: |
            FIRESTORE_DB=${{ env.FIRESTORE_DB }}
            ENV=${{ env.ENV }}
          build_service_account: projects/${{ env.PROJECT_ID }}/serviceAccounts/${{ env.BUILD_SA_EMAIL }}
