name: Deploy to Cloud Run (staging)

on:
  push:
    branches: [ "staging" ]

env:
  PROJECT_ID: prodify-474400
  REGION: us-central1
  SERVICE: hello-prodify-staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - id: deploy
        name: Deploy to Cloud Run (staging)
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          source: ./hello-prodify
          flags: >
            --allow-unauthenticated
            --set-env-vars=FIRESTORE_DB=${{ secrets.FIRESTORE_DB }},ENV=staging

      - name: Show output URL
        run: echo "${{ steps.deploy.outputs.url }}"

